config/routes.rb
Rails.application.routes.draw do


  get '/profile', to: 'profile#show'
  patch '/profile', to: 'profile#update'
  get '/profile/edit', to: 'profile#edit'


  root 'pages#home'
  


  resources :gyms do
  
    resources :gym_sessions, only: [:create, :new] do 
      member do 
        post :book
      end
    end
  end
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booked_gym_session.rb
class BookedGymSession < ApplicationRecord
  belongs_to :user
  belongs_to :gym

  
end

app/models/gym.rb
class Gym < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  belongs_to :user

  has_many :gym_sessions, dependent: :destroy
  has_many :booked_gym_sessions, dependent: :destroy
  

end

app/models/gym_session.rb
class GymSession < ApplicationRecord

  belongs_to :gym

end

app/models/profile.rb
class Profile < ApplicationRecord
  include ImageUploader::Attachment.new(:photo)
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  has_one :profile 
  has_many :booked_gym_sessions
  has_many :gyms
  
  after_create :create_profile
  
  def create_profile
    Profile.create!([
      {
        user_id: self.id
      }
    ])
  end

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user! 

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/gym_sessions_controller.rb
class GymSessionsController < ApplicationController

    before_action :set_gym, only: [:new, :create, :book]

    def new
        @gym_session = GymSession.new
    end

    def create
       
        @new_gym_session = GymSession.new(gym_session_params)
        @new_gym_session.gym = @gym
        puts @new_gym_session
        if @new_gym_session.save
         redirect_to gym_path(@gym)
        else
          redirect_to root_path
        end
    end

    def book 
        # @session = GymSession.find(params[:id])
        @booking = BookedGymSession.new
        @booking.gym = @gym 
        @booking.user = current_user
        @booking.save!
    end


    private

    def gym_session_params
      params.require(:gym_session).permit(:day_of_week, :time_from, :time_until, :hourly_price, :weeks_in_advance)
    end

    def set_gym
        @gym = Gym.find(params[:gym_id])
    end

end 

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: [:show, :edit, :update, :destroy, :new_gym_session]

  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
    @gym_sessions = @gym.gym_sessions 
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit
  end

  def book
  end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = Gym.new(gym_params)
    @gym.user = current_user
    respond_to do |format|
      if @gym.save
        format.html { redirect_to @gym, notice: 'Gym was successfully created.' }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to @gym, notice: 'Gym was successfully updated.' }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to gyms_url, notice: 'Gym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_params
      params.require(:gym).permit(:name, :description, :abn, :address, :contact_number, :image)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  
  before_action :set_profile

  def show
  end

  def edit
    authorize @profile
    
  end


  def update
    if @profile.update(profile_params)
      flash[:notice] = "profile updated"
      redirect_to profile_path
    else
      flash[:alert] = "profile not updated"
      redirect_to root_path
    end 
  end

  private
  def set_profile
    @profile = current_user.profile
  end



  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :date_of_birth, :contact_number, :address, :drivers_license, :drivers_license_image_data, :photo_data)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/gym_sessions/new.html.erb
<%# Gym Name %>

<h1><%= @gym.name %></h1>

<h2> New sessions </h2>

<%= form_with(model: [@gym, @gym_session], local: true) do |form| %>
  <% if @gym_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gym_session.errors.count, "error") %> prohibited this gym_session from being saved:</h2>

      <ul>
      <% @gym_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :days_of_week %>
    <%= form.select :day_of_week, Date::DAYNAMES %>
  </div>

  <div class="field">
    <%= form.label :time_from %>
    <%= form.text_field :time_from, id: :gym_session_time_from %>
  </div>

  <div class="field">
    <%= form.label :time_until %>
    <%= form.text_field :time_until, id: :gym_session_time_until %>
  </div>

  <div class="field">
    <%= form.label :hourly_price %>
    <%= form.text_field :hourly_price, id: :gym_session_hourly_price %>
  </div>

  <div class="field">
    <%= form.label :weeks_in_advance %>
    <%= form.text_field :weeks_in_advance, id: :gym_session_weeks_in_advance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gyms/_form.html.erb
<div class = "container">
  <%= form_with(model: gym, local: true) do |form| %>
    <% if gym.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

        <ul>
        <% gym.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


      <div class="gymname">
        <%= form.label :name %>
        <%= form.text_field :name, id: :gym_name %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description, id: :gym_description %>
      </div>

      <div class="field">
        <%= form.label :abn %>
        <%= form.text_field :abn, id: :gym_abn %>
      </div>

      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address, id: :gym_address %>
      </div>

      <div class="field">
        <%= form.label :contact_number %>
        <%= form.text_field :contact_number, id: :gym_contact_number %>
      </div>

      <div class="field">
        <%= form.label :image_data %>
        <%= form.hidden_field :image, value: gym.cached_image_data %>
        <%= form.file_field :image, id: :gym_image_data %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    
  <% end %>
</div>

app/views/gyms/edit.html.erb
<h1 class = "title">Editing Gym</h1>

<div class ="gymform">

    <%= render 'form', gym: @gym %>

</div>

    <%= link_to 'Show', @gym %> 
    <%= link_to 'Back', gyms_path %>

app/views/gyms/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class = "title">Gyms List</h1>
<div class = "gymlist">
<div style="overflow-x:auto;">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Abn</th>
      <th>Address</th>
      <th>Contact number</th>
      <th>Image data</th>
      <th>User</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @gyms.each do |gym| %>
      <tr>
        <td><%= gym.name %></td>
        <td><%= gym.description %></td>
        <td><%= gym.abn %></td>
        <td><%= gym.address %></td>
        <td><%= gym.contact_number %></td>
        <td><%= image_tag gym.image_url(:thumb) unless gym.image_data.nil? %></td>
        <td><%= link_to 'Show', gym %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%# link_to 'New Gym', new_gym_path %>

app/views/gyms/new.html.erb
<h1 class = "title">New Gym</h1>
<div class = "container">
<%= render 'form', gym: @gym %>
</div>


<%# link_to 'Back', gyms_path %>

app/views/gyms/show.html.erb
<div class = "createdgym">
    <p id="notice"><%= notice %></p>


    <p>
      <strong>Name:</strong>
      <%= @gym.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @gym.description %>
    </p>

    <p>
      <strong>Abn:</strong>
      <%= @gym.abn %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @gym.address %>
    </p>

    <p>
      <strong>Contact number:</strong>
      <%= @gym.contact_number %>
    </p>

    <p>
      <strong>Image data:</strong>
      <%= image_tag @gym.image_url(:thumb) unless @gym.image_data.nil? %>
    </p>


<% if current_user == @gym.user %>
<p>
  <%= link_to 'New session', new_gym_gym_session_path(@gym) %>
</p>
<% end %>

<% if policy(@gym).edit? %>
  <%=  link_to 'Edit', edit_gym_path(@gym) %> 
<% end %>
|
<%= link_to 'Back', gyms_path %>


<div class = "choices">
  <% @gym_sessions.each do |session| %>
    
      <%= session.id %>
      <%= session.day_of_week %>
      <%= session.time_from %>
      <%= session.time_until %>
      <%= session.weeks_in_advance %>
      <%= session.hourly_price %>
      <% unless current_user == @gym.user %>
      <%= link_to 'Book this session', book_gym_gym_session_path(@gym, session), method: :post %>
      <%end%>
  <% end %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>FitLink</title>
  <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <main>

  <div class = "navbar">
    <nav>
        <div class="menu">
        <ul>

            <li> <%= link_to 'Home', root_path %></li>
            <li> <%= link_to 'Profile', profile_path %></li>
            <li> <%= link_to 'Gyms', gyms_path %> </li>
          <% unless user_signed_in?%>

           <li>  <%=  link_to 'Sign In', new_user_session_path %> </li>
             <li> <%= link_to 'Sign Up',  new_user_registration_path %> </li>
          <% else %>

             <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </li>

          <% end %>
        </ul>  

          <div class = "brand"> <h1> Fit Link </h1> </div>


        </div>
    </nav>
  </div>

  </main>
  <%= yield %>
</body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class = "title"> About </h1> 

<div class ="about">
<p> 
    We like to bring people together and establish new connections everyday. If you are a personal trainer or a gym, it is time for you to build on your connections and be a part of the revolution. 
</p>

<br/>

<p>
    <strong> Greater Access -  </strong>
    Get access to the best gyms in Australia and maximize your coaching experience. 
</p>

<br/>

<p>
    <strong> No contract - </strong> 
    Train your clients in any available gym without the need of signing any contracts. 
</p>

</div>